### ISSUE TITLE
[BUG] Test Suite must support OCI-based registries

### ISSUE THREAD

**Issue by collivier** [lfn-cnti/testsuite#2277]
`helm repo add` doesn't work vs OCI-based registries
https://helm.sh/docs/topics/registries/

Even if it's skipped when helm_repo_url is empty, --version must be passed now when pulling the Charts.
So the following example can't work without a helm_version logic added in cnf-testsuite.yml

```
---
config_version: v2
deployments:
  helm_charts:
  - name: nginx
    helm_chart_name: nginx
    helm_repo_name: oci://ghcr.io/nginx/charts/nginx-ingress
    helm_repo_url:
    helm_values: --version 2.1.0
```

**Comment by collivier** [comment]
Please note that pulling the helm chart first and then leveraging helm_dirs

```
$ helm pull oci://registry-1.docker.io/bitnamicharts/apache --version 11.3.8 --untar
$ cat cnf-testsuite.yml 
---                                                                             
config_version: "v2"                                                            
deployments:                                                                    
  helm_dirs:                                                                    
    - name: apache                                                              
      helm_directory: apache
```

**Comment by svteb** [comment]
Below are some propositions for how the oci helm charts could be define in testsuite config.

1. Integrate with existing `helm_charts` field:

```yaml
config_version: "v2"
deployments:
  helm_charts:
    - name: coredns
      oci_registry_url: oci://registry.example.com/my-org/coredns
      chart_version: 1.8.0

      # Optional credentials
      oci_registry_credentials:
        username: oci_user
        password: supersecret

      # Optional tls support
      tls:
        ca_file: /etc/ssl/registry/ca.crt
        cert_file: /etc/ssl/registry/client.crt
        key_file: /etc/ssl/registry/client.key
      skip_tls_verify: false

      helm_values: --set replicaCount=2
      namespace: cnf-default
```

2. Create a new `oci_helm_charts` field with clear separation:

```yaml
config_version: "v2"
deployments:
  oci_helm_charts:
    - name: coredns
      registry_url: oci://registry.example.com/my-org/coredns
      chart_version: 1.8.0

      # Optional credentials
      registry_credentials:
        username: oci_user
        password: supersecret

      # Optional tls support
      tls:
        ca_file: /etc/ssl/registry/ca.crt
        cert_file: /etc/ssl/registry/client.crt
        key_file: /etc/ssl/registry/client.key
      skip_tls_verify: false

      helm_values: --set replicaCount=3
      namespace: cnf-default
```

I lean towards the second option as there would be a clearer distinction and user error would be much easier to detect (the first option looks like a nightmare in incorrect field detection). Additionally I think I would add `tls` and `chart_version` to helm as well, since we currently do not support that and adding these fields should not harm backward compatibility.
