### ISSUE TITLE
[BUG] hardcoded_ip_addresses_in_k8s_runtime_configuration fails on GeoIP addresses in configuration

### ISSUE THREAD

**Issue by neilcook** [lfn-cnti/testsuite#2282]
**Describe the bug**
The `hardcoded_ip_addresses_in_k8s_runtime_configuration` test I guess is designed to prevent CNFs from hardcoding IP addresses into config for connecting to other services. This is a laudable goal, but there are in fact other reasons for putting IP addresses in configuration. For example, we allow configuration of GeoIP DBs in configuration. These IPs cause a test failure, which should not be the case. 

I would argue that the test is not fit for purpose, because just looking for *any* IP addresses is clearly not correct. However, it would be very difficult to create a test that determined the semantics of how an IP address is being used. The test should be made non-essential or removed completely.

**To Reproduce**

1. Add some IP addresses which are not related to connecting to services to the configuration. For example in PowerDNS Helm Chart, this would look like:
```
databases:
          - name: localdb
            type: generate
            datacenters:
              - name: Amsterdam
                networks:
                  - 10.0.1.0/24
                  - 10.0.2.0/24
                  - 10.0.3.0/24
                  - 10.0.4.0/24
                  - 10.0.5.0/24
                  - 10.0.6.0/24
                lat: 52.370216
                long: 4.895168
```
2. Run the CNTi test suite
3. The `hardcoded_ip_addresses_in_k8s_runtime_configuration` test will fail

**Expected behavior**

This test should not fail just because the configuration contains any IP address. There are multiple valid reasons for the configuration to contain an IP address; GeoIP is just one of them. There might be other reasons - for example there are several scenarios in a DNS server where you can only specify an IP address, e.g. if forwarding to google DNS you have to put 8.8.8.8, there is no DNS name you can use for that.

**Device (please complete the following information):**

- OS - Any
- Distro - Any
- Version - Any
- Architecture - Any

**How will this be tested? aka Acceptance Criteria (optional)**

My suggestion is that this test is removed, or at least made not-essential.
